AllCops:
  TargetRubyVersion: 1.9
  Include:
  - Rakefile
  Exclude:
  - bat/**/*

# This one we might always want.
Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false

Lint/BlockAlignment:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/Void:
  Enabled: false

Lint/DeprecatedClassMethods:
  Enabled: false

Lint/DuplicatedKey:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Lint/StringConversionInInterpolation:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/FormatParameterMismatch:
  Enabled: false

Lint/ImplicitStringConcatenation:
  Enabled: false

Lint/LiteralInCondition:
  Enabled: false

Lint/DefEndAlignment:
  Enabled: false
