script: 'bundle exec rake --trace spec:unit:ruby'

before_install:
  - 'sudo apt-get update'
  - 'git config --global user.email "cf-bosh-eng+bosh-ci-push-pull@pivotallabs.com"'
  - 'git config --global user.name "BOSH CI Push Pull"'

install:
  - "sed -i -e '/bundler/d' Gemfile"
  - 'bundle install --local --without development'

rvm:
  - ruby-2.3.1

env:
  # limit unit test threads to 1 to avoid SimpleCov race conditions:
  # https://github.com/colszowka/simplecov/issues/305
  - BOSH_MAX_THREADS=1
