script: 'bundle exec rake --trace spec:unit:ruby ci:publish_coverage_report'

before_install:
  - 'sudo apt-get update'
  - 'git config --global user.email "cf-bosh-eng+bosh-ci-push-pull@pivotallabs.com"'
  - 'git config --global user.name "BOSH CI Push Pull"'

install:
  - 'sudo apt-get install dnsutils'
  - 'bundle install --local --without development'

rvm:
  - ruby-2.1.7

env:
  # limit unit test threads to 1 to avoid SimpleCov race conditions:
  # https://github.com/colszowka/simplecov/issues/305
  - COVERAGE=true BOSH_MAX_THREADS=1

addons:
  code_climate:
    # master branch
    repo_token: c5256f87295d0bf77f092dfa5f037b17ef17439c7342209256258084a54e410f
