---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main

inputs:
  - name: bosh-src

run:
  path: bosh-src/ci/tasks/publish-coverage.sh

params:
  CODECLIMATE_REPO_TOKEN: replace-me
  RUBY_VERSION:           2.3.1
