---
packages:
- name: nginx
  version: fd1339e8f0ffe194e1c63b8651d7192a4468dbc5
  sha1: !binary |-
    MmQ0ODQ2ZTkzZmZkYmJhYjE0MGMxNWNjYjNkZGY0ODQ4Zjg0ZmNiZA==
  fingerprint: !binary |-
    ZmQxMzM5ZThmMGZmZTE5NGUxYzYzYjg2NTFkNzE5MmE0NDY4ZGJjNQ==
  dependencies: []
- name: genisoimage
  version: !binary |-
    MDA4ZDMzMmJhMTQ3MWJjY2Y5ZDlhZWI2NGMyNThmZGQ0YmY3NjIwMQ==
  sha1: !binary |-
    MmFjZjhkYTAyNTBkYjMxZTc2MmEyMzc1NmZkMGUxMmNmYTk0N2ViOQ==
  fingerprint: !binary |-
    MDA4ZDMzMmJhMTQ3MWJjY2Y5ZDlhZWI2NGMyNThmZGQ0YmY3NjIwMQ==
  dependencies: []
- name: powerdns
  version: !binary |-
    ZTQxYmFmOGUyMzZiNWZlZDUyYmEzYzMzY2Y2NDZlNGIyZTBkNWE0ZQ==
  sha1: !binary |-
    NTdhNzZlNjVkYjA5MDAyYjFiOWEyNzdjMDQ4NzY3ZjUwZjQ4OGUzMQ==
  fingerprint: !binary |-
    ZTQxYmFmOGUyMzZiNWZlZDUyYmEzYzMzY2Y2NDZlNGIyZTBkNWE0ZQ==
  dependencies: []
- name: blobstore
  version: !binary |-
    MTU3MDVkZDdjMGMwMDdiMjU3OGY5ODJlNmM1MTllYzJkMDcyZjk5NA==
  sha1: !binary |-
    MzM5NjE1YmFjNWFmNWRmM2ZhYWNiNTBkNGViMDY0MjI2NjIxMDZhNA==
  fingerprint: !binary |-
    MTU3MDVkZDdjMGMwMDdiMjU3OGY5ODJlNmM1MTllYzJkMDcyZjk5NA==
  dependencies:
  - ruby
- name: ruby
  version: 8c1c0bba2f15f89e3129213e3877dd40e339592f
  sha1: !binary |-
    MmY4OTRjNDYxYWZiMTU4NmRjZTc4ODE4ZTNjMjUyZjg1OTQ3MzZjZg==
  fingerprint: !binary |-
    OGMxYzBiYmEyZjE1Zjg5ZTMxMjkyMTNlMzg3N2RkNDBlMzM5NTkyZg==
  dependencies: []
- name: mysql
  version: !binary |-
    ZTUzMDlhZWQ4OGY1Y2M2NjJiYzc3OTg4YTMxODc0NDYxZjdjNGZiOA==
  sha1: !binary |-
    Y2MyY2I5MjZiNmE2NDRkMjY5MjcwMGM1YWUzYmQ0ZjViODRkY2I4Mg==
  fingerprint: !binary |-
    ZTUzMDlhZWQ4OGY1Y2M2NjJiYzc3OTg4YTMxODc0NDYxZjdjNGZiOA==
  dependencies: []
- name: nats
  version: 6a31c7bb0d5ffa2a9f43c7fd7193193438e20e92
  sha1: !binary |-
    ZGVlNzBmZWY2M2FhMzVhMGQ4ZTFkOGZlNzMwYjU1OTY5MDRjNGE1OQ==
  fingerprint: !binary |-
    NmEzMWM3YmIwZDVmZmEyYTlmNDNjN2ZkNzE5MzE5MzQzOGUyMGU5Mg==
  dependencies:
  - ruby
- name: common
  version: !binary |-
    MTMyNGQzMmRiZGE0MGRhODhhYWRlMWUwN2IyMjZhMjA4NjAyYmFmZg==
  sha1: !binary |-
    OTQwN2QxZDNkYTMwZGVkMWU5NTVhY2ZjODg5OTMwNGFhNThhMGU3OA==
  fingerprint: !binary |-
    MTMyNGQzMmRiZGE0MGRhODhhYWRlMWUwN2IyMjZhMjA4NjAyYmFmZg==
  dependencies: []
- name: director
  version: !binary |-
    YTEzYTliODk5ZjBlMjYzYzFjZDI0NWNhYTUxZjczMDc0NGFhZjAxMQ==
  sha1: !binary |-
    NzQ2MmVhZjg2YjE2ZTYxM2M1MGNlYmRiZGFjZjQxZDA3NWU1MGZlMQ==
  fingerprint: !binary |-
    YTEzYTliODk5ZjBlMjYzYzFjZDI0NWNhYTUxZjczMDc0NGFhZjAxMQ==
  dependencies:
  - libpq
  - mysql
  - ruby
- name: redis
  version: !binary |-
    ZWMyN2EwYjc4NDk4NjNiYzE2MGFjNTRjZTY2N2VjYWNkMDdmYzRjYg==
  sha1: !binary |-
    MzljYTA4OTY0MzQyNjcwMzc1NzVjNzU3ZTAxYmFkYjUwYjE1ZmQwYw==
  fingerprint: !binary |-
    ZWMyN2EwYjc4NDk4NjNiYzE2MGFjNTRjZTY2N2VjYWNkMDdmYzRjYg==
  dependencies: []
- name: registry
  version: !binary |-
    YmE2MWEwOGQ2ZDg1YmMxZTk1Nzg2YmNjYTE5ZjVhNWVjNTFjNTkzNA==
  sha1: !binary |-
    NjJjODMzY2YyNzg3OTgzMTY1ZDI0NTNlZTEzNzI5ODBiMDQ4NjhjZQ==
  fingerprint: !binary |-
    YmE2MWEwOGQ2ZDg1YmMxZTk1Nzg2YmNjYTE5ZjVhNWVjNTFjNTkzNA==
  dependencies:
  - libpq
  - mysql
  - ruby
- name: libpq
  version: !binary |-
    NmFhMTlhZmIxNTNkYzI3NjkyNDY5M2RjNzI0NzYwNjY0Y2U2MTU5Mw==
  sha1: !binary |-
    N2YwZjQxODNkZWE5NjgzNzNmNzMwOTFkMWM5MTFkNWVkZWJjM2YyNQ==
  fingerprint: !binary |-
    NmFhMTlhZmIxNTNkYzI3NjkyNDY5M2RjNzI0NzYwNjY0Y2U2MTU5Mw==
  dependencies: []
- name: postgres
  version: !binary |-
    YWE3ZjViMTEwZThiMzY4ZWViOGY1ZGQwMzJlMWNhYjY2ZDg2MTRjZQ==
  sha1: !binary |-
    YTg1ZjJhMWVmYTdkZmYzNGFiNzcyZDY3MTkxZDIzMzYzOTU5Mjc2YQ==
  fingerprint: !binary |-
    YWE3ZjViMTEwZThiMzY4ZWViOGY1ZGQwMzJlMWNhYjY2ZDg2MTRjZQ==
  dependencies: []
- name: health_monitor
  version: !binary |-
    YjRkYThjMzMzYWNhYTExNWIwMmM5NDNhNWYwMmYwNjI3ZDdiYTRlMw==
  sha1: !binary |-
    NTk2ODM2ODUzZGM1NjllZWJhOTQ4ZWFiYWExMGIzZDk3NWRlNTc4ZA==
  fingerprint: !binary |-
    YjRkYThjMzMzYWNhYTExNWIwMmM5NDNhNWYwMmYwNjI3ZDdiYTRlMw==
  dependencies:
  - ruby
jobs:
- name: powerdns
  version: d160e92adf53a224df94286107b7bff0495f9fcd
  fingerprint: !binary |-
    ZDE2MGU5MmFkZjUzYTIyNGRmOTQyODYxMDdiN2JmZjA0OTVmOWZjZA==
  sha1: !binary |-
    MDJhOWQ3NWJiM2RiZjMwNmRmMGM4YTRhNWYwOTM0MGIwNjMzY2E5Mg==
- name: blobstore
  version: ec529e2dceecbf1e39679a3a53bbdccfcac0fd44
  fingerprint: !binary |-
    ZWM1MjllMmRjZWVjYmYxZTM5Njc5YTNhNTNiYmRjY2ZjYWMwZmQ0NA==
  sha1: !binary |-
    OWJjNTM3YjdmZTk3MTMxMzExMTdiY2QyNGYyOTIxOWRmNmQ5MjJlNw==
- name: nats
  version: !binary |-
    NTExODY1MjRlZDEwYmY3MTEwYThmZDcyZGEwMzZlMWFjYWY3YmExNw==
  fingerprint: !binary |-
    NTExODY1MjRlZDEwYmY3MTEwYThmZDcyZGEwMzZlMWFjYWY3YmExNw==
  sha1: !binary |-
    MDM4Nzg3NzQyYTJkMjhiNjBhOWE5NWY5ZmFmOTY4OGM1YjQ1MmUzMA==
- name: director
  version: !binary |-
    ODVjOTAxMTFiMDE5YmY1OWIzMjc0YmZmMWU1ODAxZGEyYzg1YjY5NA==
  fingerprint: !binary |-
    ODVjOTAxMTFiMDE5YmY1OWIzMjc0YmZmMWU1ODAxZGEyYzg1YjY5NA==
  sha1: !binary |-
    M2Y2MjZjYTY3OWE5MTI2YjZkNTA4ZTRkY2QwMjQzOWJjZWI3MjMwNA==
- name: redis
  version: 8b447660541a0658b2cbed6f19932c769f037188
  fingerprint: !binary |-
    OGI0NDc2NjA1NDFhMDY1OGIyY2JlZDZmMTk5MzJjNzY5ZjAzNzE4OA==
  sha1: !binary |-
    ODczODEzNGU4YTMzNTJkYzE0MDgzODRiYjE4ODM1NzFmYTM2MzNmMw==
- name: registry
  version: !binary |-
    ZmVkZmZhNzdkNmJjYzY3YTZmZjBhZmMwMDE0ZjZiNDAwNmNlODZhOA==
  fingerprint: !binary |-
    ZmVkZmZhNzdkNmJjYzY3YTZmZjBhZmMwMDE0ZjZiNDAwNmNlODZhOA==
  sha1: !binary |-
    NWNjZDA5YTIwZTAyNzdhYjQ0MzkyMGRhNzUyMTJlMGQxZjRjMWEwZg==
- name: postgres
  version: 90e43294de79754e659fc1731f515dc090f922f0
  fingerprint: !binary |-
    OTBlNDMyOTRkZTc5NzU0ZTY1OWZjMTczMWY1MTVkYzA5MGY5MjJmMA==
  sha1: !binary |-
    Y2M3YzZlMWYyNDI3MzM5NzAwNjQxODgzYTQ2ZGFiOGQ1MGJmMzQyOQ==
- name: health_monitor
  version: !binary |-
    NjNhYWQ5NWZhNTYwMTFiNTMxYWU5MTVmN2RlNGY1NjI2NDU0NTNkNA==
  fingerprint: !binary |-
    NjNhYWQ5NWZhNTYwMTFiNTMxYWU5MTVmN2RlNGY1NjI2NDU0NTNkNA==
  sha1: !binary |-
    ZWFjZGI1MTlkNmVkZjkwNDgxMjg5OTk4ZjMyN2RkMDNhZjk2ZjlmNg==
commit_hash: 5e7f33bf
uncommitted_changes: true
name: bosh
version: '127'
