inherit_from: ../.rubocop.yml

AllCops:
  Exclude:
  - spec/system/assets/**/*

SpecialGlobalVars:
  Enabled: false

CaseIndentation:
  Enabled: false

LineLength:
  Max: 132

MethodLength:
  CountComments: false
  Max: 31
