#!/usr/bin/perl
# -*- cperl -*-
#
# Copyright (C) 2009 Magnus Hagander, Redpill Linpro AB
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301 USA.
use strict;
use warnings;

use Munin::Plugin::Pgsql;

my $graphmin = ($ENV{'legacy_y_axis'} ? undef : '0');

my $pg = Munin::Plugin::Pgsql->new(
    title    => 'PostgreSQL database size',
    info     => 'Size of database',
    vlabel   => 'Size',
    basequery =>
        "SELECT datname,pg_database_size(oid) FROM pg_database %%FILTER%% ORDER BY 1",
    wildcardfilter => "WHERE datname=?",
    configquery    => "SELECT datname,datname FROM pg_database %%FILTER%% ORDER BY 1",
    suggestquery =>
        "SELECT datname FROM pg_database WHERE datallowconn AND NOT datistemplate AND NOT datname='postgres' ORDER BY 1 LIMIT 10",
    graphdraw => 'AREA',
    stack     => 1,
    base      => 1024,
    graphmin  => $graphmin
);

$pg->Process();
exit(0);
